[package]
name = "edukar-docs"
version = "0.1.0"
entrypoint = "src/edukar.typ"
authors = ["Enzo Falcon"]
repository = "https://github.com/falcone-gk/edukar-docs-template"
keywords = ["non-fiction", "basic"]
categories = ["paper", "report"]
license = "MIT"
description = "Template for Edukar exams and exams solutionaries"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
