[package]
name = "edukar"
version = "1.1.0"
entrypoint = "src/edukar.typ"
authors = ["Enzo Falcon"]
repository = "https://github.com/falcone-gk/edukar-docs-template"
description = "Template for Edukar exams and exams solutionaries"
